name = "device-sync-app"
main = "src/index.js"
compatibility_date = "2024-03-01"

# Workers KV绑定
kv_namespaces = [
  { binding = "SYNC_KV", id = "fbf94876727842b88035b9c870a43bb9" }
]

# 公共环境变量 (非敏感信息)
[vars]
VALID_USERNAME = "admin"

# 开发环境
[env.dev]
name = "device-sync-app-dev"
