name: 部署到Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 部署
    steps:
      - uses: actions/checkout@v4
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 安装依赖
        run: npm install
      
      - name: 部署到Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: '.'  # 指定工作目录
          command: deploy --name device-sync-app  # 明确指定Worker名称
          secrets: |
            JWT_SECRET
            VALID_PASSWORD
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}